package com.api.feedFormulation.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

/**
 * Entity class representing an ingredient in a feed formulation.
 * This class is used to store details about a specific ingredient,
 * including its name, crude protein content, and quantity.
 */
@Data
@Entity
@Builder
@AllArgsConstructor
public class Ingredient {

    /**
     * Unique identifier for the ingredient.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the ingredient.
     * Describes the type of ingredient used in the feed formulation.
     */
    private String name;

    /**
     * Crude protein content of the ingredient.
     * Represents the percentage of protein in the ingredient.
     */
    private double crudeProtein;

    /**
     * Quantity of the ingredient used in the feed formulation.
     * Represents the amount of the ingredient in kilograms.
     */
    private double quantity;

    /**
     * Many-to-one relationship with the FeedResponse entity.
     * Each ingredient is associated with one FeedResponse.
     */
    @ManyToOne
    @JoinColumn(name = "feed_response_id")
    private FeedResponse feedResponse;

    //default constructor
    public Ingredient() {}
}
