package com.feedformulation.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;

/**
 * Entity class representing a feed formulation response.
 * Used to store details about a specific feed formulation.
 */
@Data
@Entity
@Builder
@AllArgsConstructor
public class FeedResponse {

    /**
     * Unique identifier for the feed response, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique identifier for the feed formulation.
     */
    private String formulationId;

    /**
     * The name of the feed formulation.
     */
    private String formulationName;

    /**
     * Date of the feed formulation, in yyyy-MM-dd format.
     */
    private String date;

    /**
     * Total quantity of the feed formulation (kg).
     */
    private double quantity;

    /**
     * Target crude protein (CP) value of the feed formulation.
     */
    private double targetCpValue;

    /**
     * List of ingredients used in the feed formulation.
     * Represents a one-to-many relationship with Ingredient.
     */
    @OneToMany(mappedBy = "feedResponse", cascade = CascadeType.ALL)
    private List<Ingredient> ingredients = new ArrayList<>();

    // Default constructor
    public FeedResponse() {}
}
